export const predefinedSpecies = {
  Mammals: [
    "Mammalia",
    "Canis familiaris",
    "Canis latrans",
    "Felis catus",
    "Castor canadensis",
    "Ondatra zibethicus",
    "Marmota monax",
    "Sylvilagus floridanus",
    "Sciurus carolinensis",
    "Sciurus niger",
    "Tamias Striatus",
    "Lasionycteris noctivagans",
    "Myotis lucifugus",
    "Eptesicus fuscus",
    "Lasiurus borealis",
    "Procyon lotor",
    "Rattus norvegicus",
    "Apodemus sylvaticus",
    "Peromyscus maniculatus",
    "Microtus pennsylvanicus",
    "Mephitis mephitis",
    "Neovision vision",
    "Odocoileus virginianus",
    "Vulpes vulpes",
    "Lontra canadensis",
    "Didelphis virginiana",
  ],
  Reptiles: [
    "Reptilia",
    "Trachemys scripta elegans",
    "Chelydra Serpentina",
    "Chrysemys picta",
    "Apalone spinifera",
    "Thamnophis sirtalis",
    "Storeria dekayi",
    "Nerodia sipedon",
  ],
  Amphibians: [
    "Amphibia",
    "Lithobates catesbeianus",
    "Anaxyrus americanus",
    "Pseudacris crucifer",
    "Pseudacris triseriata",
    "Lithobates pipiens",
    "Rana clamitans",
  ],
  Birds: [
    "Aves",
    "Anas platyrhynchos",
    "Branta canadensis",
    "Larus delawarensis",
    "Columba livia",
    "Sturnus vulgaris",
    "Passer domesticus",
    "Turdus migratorius",
    "Agelaius phoeniceus",
    "Corvus brachyrhynchos",
    "Nannopterum auritum",
    "Ardea herodias",
    "Nycticorax nycticorax",
    "Accipiter cooperii",
    "Actitis macularius",
    "Aix sponsa",
    "Anas acuta",
    "Anser albifrons",
    "Anser caerulescens",
    "Archilochus colubris",
    "Ardea alba",
    "Aythya affinis",
    "Aythya americana",
    "Aythya marila",
    "Bombycilla cedrorum",
    "Botaurus lentiginosus",
    "Branta hutchinsii",
    "Bubo virginianus",
    "Bucephala albeola",
    "Bucephala clangula",
    "Buteo jamaicensis",
    "Butorides virescens",
    "Cardinalis cardinalis",
    "Cathartes aura",
    "Chaetura pelagica",
    "Charadrius vociferus",
    "Colaptes auratus",
    "Cyanocitta cristata",
    "Cygnus olor",
    "Dumetella carolinensis",
    "Falco peregrinus",
    "Falco sparverius",
    "Gavia immer",
    "Grus canadensis",
    "Ixobrychus exilis",
    "Junco hyemalis",
    "Larus argentatus",
    "Lophodytes cucullatus",
    "Megaceryle alcyon",
    "Melanerpes erythrocephalus",
    "Melospiza melodia",
    "Mergus merganser",
    "Mergus serrator",
    "Nyctanassa violacea",
    "Pandion haliaetus",
    "Passerina cyanea",
    "Pheucticus ludovicianus",
    "Podiceps auritus",
    "Podilymbus podiceps",
    "Poecile atricapillus",
    "Quiscalus quiscula",
    "Spinus tristis",
    "Spiza americana",
    "Tyrannus tyrannus",
    "Zenaida macroura",
    "Zonotrichia albicollis",
  ],
  Fish: [
    "Chordata",
    "Cyprinus carpio",
    "Lepomis macrochirus",
    "Micropterus salmoides",
    "Ictalurus punctatus",
    "Micropterus dolomieu",
    "Esox lucius",
    "Perca flavescens",
    "Pomoxis nigromaculatus",
    "Sander vitreus",
    "Lepomis gibbosus",
    "Ameiurus nebulosus",
    "Aplodinotus grunniens",
    "Amia calva",
    "Catostomus commersonii",
    "Dorosoma cepedianum",
    "Hypophthalmichthys molitrix",
    "Notemigonus crysoleucas",
    "Oncorhynchus mykiss",
    "Pimephales promelas",
    "Salvelinus namaycush",
  ],
};

// Insects: ["Arthropoda"], // Add insect species if available
